
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BreadcrumbWidget': typeof import("../components/BreadcrumbWidget.vue")['default']
    'CreatePlaylist': typeof import("../components/CreatePlaylist.vue")['default']
    'CustomButton': typeof import("../components/CustomButton.vue")['default']
    'LoaderComponent': typeof import("../components/LoaderComponent.vue")['default']
    'MovieDescription': typeof import("../components/MovieDescription.vue")['default']
    'MovieSources': typeof import("../components/MovieSources.vue")['default']
    'SettingOffcanvas': typeof import("../components/SettingOffcanvas.vue")['default']
    'BlogDetailMetaList': typeof import("../components/blog/DetailMetaList.vue")['default']
    'BlogCommentsFormWidget': typeof import("../components/blog/comments/FormWidget.vue")['default']
    'BlogCommentsListWidget': typeof import("../components/blog/comments/ListWidget.vue")['default']
    'BlogSidebarAboutPage': typeof import("../components/blog/sidebar/AboutPage.vue")['default']
    'BlogSidebarArchiveWidget': typeof import("../components/blog/sidebar/ArchiveWidget.vue")['default']
    'BlogSidebarCategoriesWidget': typeof import("../components/blog/sidebar/CategoriesWidget.vue")['default']
    'BlogSidebarFollowUs': typeof import("../components/blog/sidebar/FollowUs.vue")['default']
    'BlogSidebarProductWidget': typeof import("../components/blog/sidebar/ProductWidget.vue")['default']
    'BlogSidebarRecentPost': typeof import("../components/blog/sidebar/RecentPost.vue")['default']
    'BlogSidebarRecentWidget': typeof import("../components/blog/sidebar/RecentWidget.vue")['default']
    'BlogSidebarTagsWidget': typeof import("../components/blog/sidebar/TagsWidget.vue")['default']
    'BrandLogo': typeof import("../components/brand/BrandLogo.vue")['default']
    'CardsCardBlogGrid': typeof import("../components/cards/CardBlogGrid.vue")['default']
    'CardsCardBlogList': typeof import("../components/cards/CardBlogList.vue")['default']
    'CardsCardCastGrid': typeof import("../components/cards/CardCastGrid.vue")['default']
    'CardsCardGenresGrid': typeof import("../components/cards/CardGenresGrid.vue")['default']
    'CardsCardStyle': typeof import("../components/cards/CardStyle.vue")['default']
    'CardsCastCard': typeof import("../components/cards/CastCard.vue")['default']
    'CardsContinueWatchCard': typeof import("../components/cards/ContinueWatchCard.vue")['default']
    'CardsEpisodeCard': typeof import("../components/cards/EpisodeCard.vue")['default']
    'CardsGenersCard': typeof import("../components/cards/GenersCard.vue")['default']
    'CardsPersonalityCard': typeof import("../components/cards/PersonalityCard.vue")['default']
    'CardsProfileCard': typeof import("../components/cards/ProfileCard.vue")['default']
    'CardsTagsCard': typeof import("../components/cards/TagsCard.vue")['default']
    'CardsTopTenCard': typeof import("../components/cards/TopTenCard.vue")['default']
    'CardsWatchlistCard': typeof import("../components/cards/WatchlistCard.vue")['default']
    'Counter': typeof import("../components/counter/Counter.vue")['default']
    'MerchandiseCategoryGridView': typeof import("../components/merchandise/CategoryGridView.vue")['default']
    'MerchandiseCategoryListView': typeof import("../components/merchandise/CategoryListView.vue")['default']
    'MerchandiseCheckoutCard': typeof import("../components/merchandise/CheckoutCard.vue")['default']
    'MerchandiseProductCard': typeof import("../components/merchandise/ProductCard.vue")['default']
    'MerchandiseProductFsLightBox': typeof import("../components/merchandise/ProductFsLightBox.vue")['default']
    'MerchandiseShopCategorySidebar': typeof import("../components/merchandise/ShopCategorySidebar.vue")['default']
    'MerchandiseWishlistCard': typeof import("../components/merchandise/WishlistCard.vue")['default']
    'MerchandiseCartTotal': typeof import("../components/merchandise/cart/CartTotal.vue")['default']
    'MerchandiseCartOffCanvasCart': typeof import("../components/merchandise/cart/OffCanvasCart.vue")['default']
    'MerchandiseCartProductCart': typeof import("../components/merchandise/cart/ProductCart.vue")['default']
    'MerchandisePartialsFooterMerchandise': typeof import("../components/merchandise/partials/FooterMerchandise.vue")['default']
    'MerchandisePartialsHeaderMerchandise': typeof import("../components/merchandise/partials/HeaderMerchandise.vue")['default']
    'PartialsFooterDefault': typeof import("../components/partials/FooterDefault.vue")['default']
    'PartialsHeaderDefault': typeof import("../components/partials/HeaderDefault.vue")['default']
    'PluginsVideoPlayer': typeof import("../components/plugins/VideoPlayer.vue")['default']
    'SectionsBestOfInternationalShows': typeof import("../components/sections/BestOfInternationalShows.vue")['default']
    'SectionsContinueWatching': typeof import("../components/sections/ContinueWatching.vue")['default']
    'SectionsLatestMovies': typeof import("../components/sections/LatestMovies.vue")['default']
    'SectionsMovieGeners': typeof import("../components/sections/MovieGeners.vue")['default']
    'SectionsMoviesRecommendedForYou': typeof import("../components/sections/MoviesRecommendedForYou.vue")['default']
    'SectionsOnlyOnStreamit': typeof import("../components/sections/OnlyOnStreamit.vue")['default']
    'SectionsParallexSection': typeof import("../components/sections/ParallexSection.vue")['default']
    'SectionsPopularMovies': typeof import("../components/sections/PopularMovies.vue")['default']
    'SectionsPopularVideos': typeof import("../components/sections/PopularVideos.vue")['default']
    'SectionsProductSection': typeof import("../components/sections/ProductSection.vue")['default']
    'SectionsRecommendedForYou': typeof import("../components/sections/RecommendedForYou.vue")['default']
    'SectionsRecommendedTVShow': typeof import("../components/sections/RecommendedTVShow.vue")['default']
    'SectionsShowsWeRecommend': typeof import("../components/sections/ShowsWeRecommend.vue")['default']
    'SectionsSpecials&LatestMovies': typeof import("../components/sections/Specials&LatestMovies.vue")['default']
    'SectionsSuggestedBlock': typeof import("../components/sections/SuggestedBlock.vue")['default']
    'SectionsTVPopularShows': typeof import("../components/sections/TVPopularShows.vue")['default']
    'SectionsTabSlider': typeof import("../components/sections/TabSlider.vue")['default']
    'SectionsTopPicsForYou': typeof import("../components/sections/TopPicsForYou.vue")['default']
    'SectionsTopTenMoviesToWatch': typeof import("../components/sections/TopTenMoviesToWatch.vue")['default']
    'SectionsTrendingSection': typeof import("../components/sections/TrendingSection.vue")['default']
    'SectionsUpcomingMovies': typeof import("../components/sections/UpcomingMovies.vue")['default']
    'SectionsVideosRecommendedForYou': typeof import("../components/sections/VideosRecommendedForYou.vue")['default']
    'SectionsYourFavouritePersonality': typeof import("../components/sections/YourFavouritePersonality.vue")['default']
    'SliderHomeHeroSlider': typeof import("../components/slider/HomeHeroSlider.vue")['default']
    'SliderHomeVerticalSlider': typeof import("../components/slider/HomeVerticalSlider.vue")['default']
    'SliderMovieHeroSlider': typeof import("../components/slider/MovieHeroSlider.vue")['default']
    'SliderOttHeroSlider': typeof import("../components/slider/OttHeroSlider.vue")['default']
    'SliderSectionSlider': typeof import("../components/slider/SectionSlider.vue")['default']
    'SliderShopHeroProductSlider': typeof import("../components/slider/ShopHeroProductSlider.vue")['default']
    'SliderTvShowHeroSlider': typeof import("../components/slider/TvShowHeroSlider.vue")['default']
    'SliderVerticalSectionSlider': typeof import("../components/slider/VerticalSectionSlider.vue")['default']
    'SliderVideoHeroSlider': typeof import("../components/slider/VideoHeroSlider.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'BAccordion': typeof import("bootstrap-vue-next")['BAccordion']
    'BAccordionItem': typeof import("bootstrap-vue-next")['BAccordionItem']
    'BAlert': typeof import("bootstrap-vue-next")['BAlert']
    'BAvatar': typeof import("bootstrap-vue-next")['BAvatar']
    'BAvatarGroup': typeof import("bootstrap-vue-next")['BAvatarGroup']
    'BBadge': typeof import("bootstrap-vue-next")['BBadge']
    'BBreadcrumb': typeof import("bootstrap-vue-next")['BBreadcrumb']
    'BBreadcrumbItem': typeof import("bootstrap-vue-next")['BBreadcrumbItem']
    'BButton': typeof import("bootstrap-vue-next")['BButton']
    'BButtonGroup': typeof import("bootstrap-vue-next")['BButtonGroup']
    'BButtonToolbar': typeof import("bootstrap-vue-next")['BButtonToolbar']
    'BCard': typeof import("bootstrap-vue-next")['BCard']
    'BCardBody': typeof import("bootstrap-vue-next")['BCardBody']
    'BCardFooter': typeof import("bootstrap-vue-next")['BCardFooter']
    'BCardGroup': typeof import("bootstrap-vue-next")['BCardGroup']
    'BCardHeader': typeof import("bootstrap-vue-next")['BCardHeader']
    'BCardImg': typeof import("bootstrap-vue-next")['BCardImg']
    'BCardSubtitle': typeof import("bootstrap-vue-next")['BCardSubtitle']
    'BCardText': typeof import("bootstrap-vue-next")['BCardText']
    'BCardTitle': typeof import("bootstrap-vue-next")['BCardTitle']
    'BCarousel': typeof import("bootstrap-vue-next")['BCarousel']
    'BCarouselSlide': typeof import("bootstrap-vue-next")['BCarouselSlide']
    'BCloseButton': typeof import("bootstrap-vue-next")['BCloseButton']
    'BCol': typeof import("bootstrap-vue-next")['BCol']
    'BCollapse': typeof import("bootstrap-vue-next")['BCollapse']
    'BContainer': typeof import("bootstrap-vue-next")['BContainer']
    'BDropdown': typeof import("bootstrap-vue-next")['BDropdown']
    'BDropdownDivider': typeof import("bootstrap-vue-next")['BDropdownDivider']
    'BDropdownForm': typeof import("bootstrap-vue-next")['BDropdownForm']
    'BDropdownGroup': typeof import("bootstrap-vue-next")['BDropdownGroup']
    'BDropdownHeader': typeof import("bootstrap-vue-next")['BDropdownHeader']
    'BDropdownItem': typeof import("bootstrap-vue-next")['BDropdownItem']
    'BDropdownItemButton': typeof import("bootstrap-vue-next")['BDropdownItemButton']
    'BDropdownText': typeof import("bootstrap-vue-next")['BDropdownText']
    'BForm': typeof import("bootstrap-vue-next")['BForm']
    'BFormCheckbox': typeof import("bootstrap-vue-next")['BFormCheckbox']
    'BFormCheckboxGroup': typeof import("bootstrap-vue-next")['BFormCheckboxGroup']
    'BFormFile': typeof import("bootstrap-vue-next")['BFormFile']
    'BFormFloatingLabel': typeof import("bootstrap-vue-next")['BFormFloatingLabel']
    'BFormGroup': typeof import("bootstrap-vue-next")['BFormGroup']
    'BFormInput': typeof import("bootstrap-vue-next")['BFormInput']
    'BFormInvalidFeedback': typeof import("bootstrap-vue-next")['BFormInvalidFeedback']
    'BFormRadio': typeof import("bootstrap-vue-next")['BFormRadio']
    'BFormRadioGroup': typeof import("bootstrap-vue-next")['BFormRadioGroup']
    'BFormRow': typeof import("bootstrap-vue-next")['BFormRow']
    'BFormSelect': typeof import("bootstrap-vue-next")['BFormSelect']
    'BFormSelectOption': typeof import("bootstrap-vue-next")['BFormSelectOption']
    'BFormSelectOptionGroup': typeof import("bootstrap-vue-next")['BFormSelectOptionGroup']
    'BFormSpinbutton': typeof import("bootstrap-vue-next")['BFormSpinbutton']
    'BFormTag': typeof import("bootstrap-vue-next")['BFormTag']
    'BFormTags': typeof import("bootstrap-vue-next")['BFormTags']
    'BFormText': typeof import("bootstrap-vue-next")['BFormText']
    'BFormTextarea': typeof import("bootstrap-vue-next")['BFormTextarea']
    'BFormValidFeedback': typeof import("bootstrap-vue-next")['BFormValidFeedback']
    'BImg': typeof import("bootstrap-vue-next")['BImg']
    'BInputGroup': typeof import("bootstrap-vue-next")['BInputGroup']
    'BInputGroupAddon': typeof import("bootstrap-vue-next")['BInputGroupAddon']
    'BInputGroupAppend': typeof import("bootstrap-vue-next")['BInputGroupAppend']
    'BInputGroupPrepend': typeof import("bootstrap-vue-next")['BInputGroupPrepend']
    'BInputGroupText': typeof import("bootstrap-vue-next")['BInputGroupText']
    'BLink': typeof import("bootstrap-vue-next")['BLink']
    'BListGroup': typeof import("bootstrap-vue-next")['BListGroup']
    'BListGroupItem': typeof import("bootstrap-vue-next")['BListGroupItem']
    'BModal': typeof import("bootstrap-vue-next")['BModal']
    'BNav': typeof import("bootstrap-vue-next")['BNav']
    'BNavForm': typeof import("bootstrap-vue-next")['BNavForm']
    'BNavItem': typeof import("bootstrap-vue-next")['BNavItem']
    'BNavItemDropdown': typeof import("bootstrap-vue-next")['BNavItemDropdown']
    'BNavText': typeof import("bootstrap-vue-next")['BNavText']
    'BNavbar': typeof import("bootstrap-vue-next")['BNavbar']
    'BNavbarBrand': typeof import("bootstrap-vue-next")['BNavbarBrand']
    'BNavbarNav': typeof import("bootstrap-vue-next")['BNavbarNav']
    'BNavbarToggle': typeof import("bootstrap-vue-next")['BNavbarToggle']
    'BOffcanvas': typeof import("bootstrap-vue-next")['BOffcanvas']
    'BOverlay': typeof import("bootstrap-vue-next")['BOverlay']
    'BPagination': typeof import("bootstrap-vue-next")['BPagination']
    'BPlaceholder': typeof import("bootstrap-vue-next")['BPlaceholder']
    'BPlaceholderButton': typeof import("bootstrap-vue-next")['BPlaceholderButton']
    'BPlaceholderCard': typeof import("bootstrap-vue-next")['BPlaceholderCard']
    'BPlaceholderTable': typeof import("bootstrap-vue-next")['BPlaceholderTable']
    'BPlaceholderWrapper': typeof import("bootstrap-vue-next")['BPlaceholderWrapper']
    'BPopover': typeof import("bootstrap-vue-next")['BPopover']
    'BProgress': typeof import("bootstrap-vue-next")['BProgress']
    'BProgressBar': typeof import("bootstrap-vue-next")['BProgressBar']
    'BRow': typeof import("bootstrap-vue-next")['BRow']
    'BSpinner': typeof import("bootstrap-vue-next")['BSpinner']
    'BTab': typeof import("bootstrap-vue-next")['BTab']
    'BTable': typeof import("bootstrap-vue-next")['BTable']
    'BTableLite': typeof import("bootstrap-vue-next")['BTableLite']
    'BTableSimple': typeof import("bootstrap-vue-next")['BTableSimple']
    'BTabs': typeof import("bootstrap-vue-next")['BTabs']
    'BTbody': typeof import("bootstrap-vue-next")['BTbody']
    'BTd': typeof import("bootstrap-vue-next")['BTd']
    'BTfoot': typeof import("bootstrap-vue-next")['BTfoot']
    'BTh': typeof import("bootstrap-vue-next")['BTh']
    'BThead': typeof import("bootstrap-vue-next")['BThead']
    'BToast': typeof import("bootstrap-vue-next")['BToast']
    'BToaster': typeof import("bootstrap-vue-next")['BToaster']
    'BTooltip': typeof import("bootstrap-vue-next")['BTooltip']
    'BTr': typeof import("bootstrap-vue-next")['BTr']
    'BTransition': typeof import("bootstrap-vue-next")['BTransition']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBreadcrumbWidget': typeof import("../components/BreadcrumbWidget.vue")['default']
    'LazyCreatePlaylist': typeof import("../components/CreatePlaylist.vue")['default']
    'LazyCustomButton': typeof import("../components/CustomButton.vue")['default']
    'LazyLoaderComponent': typeof import("../components/LoaderComponent.vue")['default']
    'LazyMovieDescription': typeof import("../components/MovieDescription.vue")['default']
    'LazyMovieSources': typeof import("../components/MovieSources.vue")['default']
    'LazySettingOffcanvas': typeof import("../components/SettingOffcanvas.vue")['default']
    'LazyBlogDetailMetaList': typeof import("../components/blog/DetailMetaList.vue")['default']
    'LazyBlogCommentsFormWidget': typeof import("../components/blog/comments/FormWidget.vue")['default']
    'LazyBlogCommentsListWidget': typeof import("../components/blog/comments/ListWidget.vue")['default']
    'LazyBlogSidebarAboutPage': typeof import("../components/blog/sidebar/AboutPage.vue")['default']
    'LazyBlogSidebarArchiveWidget': typeof import("../components/blog/sidebar/ArchiveWidget.vue")['default']
    'LazyBlogSidebarCategoriesWidget': typeof import("../components/blog/sidebar/CategoriesWidget.vue")['default']
    'LazyBlogSidebarFollowUs': typeof import("../components/blog/sidebar/FollowUs.vue")['default']
    'LazyBlogSidebarProductWidget': typeof import("../components/blog/sidebar/ProductWidget.vue")['default']
    'LazyBlogSidebarRecentPost': typeof import("../components/blog/sidebar/RecentPost.vue")['default']
    'LazyBlogSidebarRecentWidget': typeof import("../components/blog/sidebar/RecentWidget.vue")['default']
    'LazyBlogSidebarTagsWidget': typeof import("../components/blog/sidebar/TagsWidget.vue")['default']
    'LazyBrandLogo': typeof import("../components/brand/BrandLogo.vue")['default']
    'LazyCardsCardBlogGrid': typeof import("../components/cards/CardBlogGrid.vue")['default']
    'LazyCardsCardBlogList': typeof import("../components/cards/CardBlogList.vue")['default']
    'LazyCardsCardCastGrid': typeof import("../components/cards/CardCastGrid.vue")['default']
    'LazyCardsCardGenresGrid': typeof import("../components/cards/CardGenresGrid.vue")['default']
    'LazyCardsCardStyle': typeof import("../components/cards/CardStyle.vue")['default']
    'LazyCardsCastCard': typeof import("../components/cards/CastCard.vue")['default']
    'LazyCardsContinueWatchCard': typeof import("../components/cards/ContinueWatchCard.vue")['default']
    'LazyCardsEpisodeCard': typeof import("../components/cards/EpisodeCard.vue")['default']
    'LazyCardsGenersCard': typeof import("../components/cards/GenersCard.vue")['default']
    'LazyCardsPersonalityCard': typeof import("../components/cards/PersonalityCard.vue")['default']
    'LazyCardsProfileCard': typeof import("../components/cards/ProfileCard.vue")['default']
    'LazyCardsTagsCard': typeof import("../components/cards/TagsCard.vue")['default']
    'LazyCardsTopTenCard': typeof import("../components/cards/TopTenCard.vue")['default']
    'LazyCardsWatchlistCard': typeof import("../components/cards/WatchlistCard.vue")['default']
    'LazyCounter': typeof import("../components/counter/Counter.vue")['default']
    'LazyMerchandiseCategoryGridView': typeof import("../components/merchandise/CategoryGridView.vue")['default']
    'LazyMerchandiseCategoryListView': typeof import("../components/merchandise/CategoryListView.vue")['default']
    'LazyMerchandiseCheckoutCard': typeof import("../components/merchandise/CheckoutCard.vue")['default']
    'LazyMerchandiseProductCard': typeof import("../components/merchandise/ProductCard.vue")['default']
    'LazyMerchandiseProductFsLightBox': typeof import("../components/merchandise/ProductFsLightBox.vue")['default']
    'LazyMerchandiseShopCategorySidebar': typeof import("../components/merchandise/ShopCategorySidebar.vue")['default']
    'LazyMerchandiseWishlistCard': typeof import("../components/merchandise/WishlistCard.vue")['default']
    'LazyMerchandiseCartTotal': typeof import("../components/merchandise/cart/CartTotal.vue")['default']
    'LazyMerchandiseCartOffCanvasCart': typeof import("../components/merchandise/cart/OffCanvasCart.vue")['default']
    'LazyMerchandiseCartProductCart': typeof import("../components/merchandise/cart/ProductCart.vue")['default']
    'LazyMerchandisePartialsFooterMerchandise': typeof import("../components/merchandise/partials/FooterMerchandise.vue")['default']
    'LazyMerchandisePartialsHeaderMerchandise': typeof import("../components/merchandise/partials/HeaderMerchandise.vue")['default']
    'LazyPartialsFooterDefault': typeof import("../components/partials/FooterDefault.vue")['default']
    'LazyPartialsHeaderDefault': typeof import("../components/partials/HeaderDefault.vue")['default']
    'LazyPluginsVideoPlayer': typeof import("../components/plugins/VideoPlayer.vue")['default']
    'LazySectionsBestOfInternationalShows': typeof import("../components/sections/BestOfInternationalShows.vue")['default']
    'LazySectionsContinueWatching': typeof import("../components/sections/ContinueWatching.vue")['default']
    'LazySectionsLatestMovies': typeof import("../components/sections/LatestMovies.vue")['default']
    'LazySectionsMovieGeners': typeof import("../components/sections/MovieGeners.vue")['default']
    'LazySectionsMoviesRecommendedForYou': typeof import("../components/sections/MoviesRecommendedForYou.vue")['default']
    'LazySectionsOnlyOnStreamit': typeof import("../components/sections/OnlyOnStreamit.vue")['default']
    'LazySectionsParallexSection': typeof import("../components/sections/ParallexSection.vue")['default']
    'LazySectionsPopularMovies': typeof import("../components/sections/PopularMovies.vue")['default']
    'LazySectionsPopularVideos': typeof import("../components/sections/PopularVideos.vue")['default']
    'LazySectionsProductSection': typeof import("../components/sections/ProductSection.vue")['default']
    'LazySectionsRecommendedForYou': typeof import("../components/sections/RecommendedForYou.vue")['default']
    'LazySectionsRecommendedTVShow': typeof import("../components/sections/RecommendedTVShow.vue")['default']
    'LazySectionsShowsWeRecommend': typeof import("../components/sections/ShowsWeRecommend.vue")['default']
    'LazySectionsSpecials&LatestMovies': typeof import("../components/sections/Specials&LatestMovies.vue")['default']
    'LazySectionsSuggestedBlock': typeof import("../components/sections/SuggestedBlock.vue")['default']
    'LazySectionsTVPopularShows': typeof import("../components/sections/TVPopularShows.vue")['default']
    'LazySectionsTabSlider': typeof import("../components/sections/TabSlider.vue")['default']
    'LazySectionsTopPicsForYou': typeof import("../components/sections/TopPicsForYou.vue")['default']
    'LazySectionsTopTenMoviesToWatch': typeof import("../components/sections/TopTenMoviesToWatch.vue")['default']
    'LazySectionsTrendingSection': typeof import("../components/sections/TrendingSection.vue")['default']
    'LazySectionsUpcomingMovies': typeof import("../components/sections/UpcomingMovies.vue")['default']
    'LazySectionsVideosRecommendedForYou': typeof import("../components/sections/VideosRecommendedForYou.vue")['default']
    'LazySectionsYourFavouritePersonality': typeof import("../components/sections/YourFavouritePersonality.vue")['default']
    'LazySliderHomeHeroSlider': typeof import("../components/slider/HomeHeroSlider.vue")['default']
    'LazySliderHomeVerticalSlider': typeof import("../components/slider/HomeVerticalSlider.vue")['default']
    'LazySliderMovieHeroSlider': typeof import("../components/slider/MovieHeroSlider.vue")['default']
    'LazySliderOttHeroSlider': typeof import("../components/slider/OttHeroSlider.vue")['default']
    'LazySliderSectionSlider': typeof import("../components/slider/SectionSlider.vue")['default']
    'LazySliderShopHeroProductSlider': typeof import("../components/slider/ShopHeroProductSlider.vue")['default']
    'LazySliderTvShowHeroSlider': typeof import("../components/slider/TvShowHeroSlider.vue")['default']
    'LazySliderVerticalSectionSlider': typeof import("../components/slider/VerticalSectionSlider.vue")['default']
    'LazySliderVideoHeroSlider': typeof import("../components/slider/VideoHeroSlider.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyBAccordion': typeof import("bootstrap-vue-next")['BAccordion']
    'LazyBAccordionItem': typeof import("bootstrap-vue-next")['BAccordionItem']
    'LazyBAlert': typeof import("bootstrap-vue-next")['BAlert']
    'LazyBAvatar': typeof import("bootstrap-vue-next")['BAvatar']
    'LazyBAvatarGroup': typeof import("bootstrap-vue-next")['BAvatarGroup']
    'LazyBBadge': typeof import("bootstrap-vue-next")['BBadge']
    'LazyBBreadcrumb': typeof import("bootstrap-vue-next")['BBreadcrumb']
    'LazyBBreadcrumbItem': typeof import("bootstrap-vue-next")['BBreadcrumbItem']
    'LazyBButton': typeof import("bootstrap-vue-next")['BButton']
    'LazyBButtonGroup': typeof import("bootstrap-vue-next")['BButtonGroup']
    'LazyBButtonToolbar': typeof import("bootstrap-vue-next")['BButtonToolbar']
    'LazyBCard': typeof import("bootstrap-vue-next")['BCard']
    'LazyBCardBody': typeof import("bootstrap-vue-next")['BCardBody']
    'LazyBCardFooter': typeof import("bootstrap-vue-next")['BCardFooter']
    'LazyBCardGroup': typeof import("bootstrap-vue-next")['BCardGroup']
    'LazyBCardHeader': typeof import("bootstrap-vue-next")['BCardHeader']
    'LazyBCardImg': typeof import("bootstrap-vue-next")['BCardImg']
    'LazyBCardSubtitle': typeof import("bootstrap-vue-next")['BCardSubtitle']
    'LazyBCardText': typeof import("bootstrap-vue-next")['BCardText']
    'LazyBCardTitle': typeof import("bootstrap-vue-next")['BCardTitle']
    'LazyBCarousel': typeof import("bootstrap-vue-next")['BCarousel']
    'LazyBCarouselSlide': typeof import("bootstrap-vue-next")['BCarouselSlide']
    'LazyBCloseButton': typeof import("bootstrap-vue-next")['BCloseButton']
    'LazyBCol': typeof import("bootstrap-vue-next")['BCol']
    'LazyBCollapse': typeof import("bootstrap-vue-next")['BCollapse']
    'LazyBContainer': typeof import("bootstrap-vue-next")['BContainer']
    'LazyBDropdown': typeof import("bootstrap-vue-next")['BDropdown']
    'LazyBDropdownDivider': typeof import("bootstrap-vue-next")['BDropdownDivider']
    'LazyBDropdownForm': typeof import("bootstrap-vue-next")['BDropdownForm']
    'LazyBDropdownGroup': typeof import("bootstrap-vue-next")['BDropdownGroup']
    'LazyBDropdownHeader': typeof import("bootstrap-vue-next")['BDropdownHeader']
    'LazyBDropdownItem': typeof import("bootstrap-vue-next")['BDropdownItem']
    'LazyBDropdownItemButton': typeof import("bootstrap-vue-next")['BDropdownItemButton']
    'LazyBDropdownText': typeof import("bootstrap-vue-next")['BDropdownText']
    'LazyBForm': typeof import("bootstrap-vue-next")['BForm']
    'LazyBFormCheckbox': typeof import("bootstrap-vue-next")['BFormCheckbox']
    'LazyBFormCheckboxGroup': typeof import("bootstrap-vue-next")['BFormCheckboxGroup']
    'LazyBFormFile': typeof import("bootstrap-vue-next")['BFormFile']
    'LazyBFormFloatingLabel': typeof import("bootstrap-vue-next")['BFormFloatingLabel']
    'LazyBFormGroup': typeof import("bootstrap-vue-next")['BFormGroup']
    'LazyBFormInput': typeof import("bootstrap-vue-next")['BFormInput']
    'LazyBFormInvalidFeedback': typeof import("bootstrap-vue-next")['BFormInvalidFeedback']
    'LazyBFormRadio': typeof import("bootstrap-vue-next")['BFormRadio']
    'LazyBFormRadioGroup': typeof import("bootstrap-vue-next")['BFormRadioGroup']
    'LazyBFormRow': typeof import("bootstrap-vue-next")['BFormRow']
    'LazyBFormSelect': typeof import("bootstrap-vue-next")['BFormSelect']
    'LazyBFormSelectOption': typeof import("bootstrap-vue-next")['BFormSelectOption']
    'LazyBFormSelectOptionGroup': typeof import("bootstrap-vue-next")['BFormSelectOptionGroup']
    'LazyBFormSpinbutton': typeof import("bootstrap-vue-next")['BFormSpinbutton']
    'LazyBFormTag': typeof import("bootstrap-vue-next")['BFormTag']
    'LazyBFormTags': typeof import("bootstrap-vue-next")['BFormTags']
    'LazyBFormText': typeof import("bootstrap-vue-next")['BFormText']
    'LazyBFormTextarea': typeof import("bootstrap-vue-next")['BFormTextarea']
    'LazyBFormValidFeedback': typeof import("bootstrap-vue-next")['BFormValidFeedback']
    'LazyBImg': typeof import("bootstrap-vue-next")['BImg']
    'LazyBInputGroup': typeof import("bootstrap-vue-next")['BInputGroup']
    'LazyBInputGroupAddon': typeof import("bootstrap-vue-next")['BInputGroupAddon']
    'LazyBInputGroupAppend': typeof import("bootstrap-vue-next")['BInputGroupAppend']
    'LazyBInputGroupPrepend': typeof import("bootstrap-vue-next")['BInputGroupPrepend']
    'LazyBInputGroupText': typeof import("bootstrap-vue-next")['BInputGroupText']
    'LazyBLink': typeof import("bootstrap-vue-next")['BLink']
    'LazyBListGroup': typeof import("bootstrap-vue-next")['BListGroup']
    'LazyBListGroupItem': typeof import("bootstrap-vue-next")['BListGroupItem']
    'LazyBModal': typeof import("bootstrap-vue-next")['BModal']
    'LazyBNav': typeof import("bootstrap-vue-next")['BNav']
    'LazyBNavForm': typeof import("bootstrap-vue-next")['BNavForm']
    'LazyBNavItem': typeof import("bootstrap-vue-next")['BNavItem']
    'LazyBNavItemDropdown': typeof import("bootstrap-vue-next")['BNavItemDropdown']
    'LazyBNavText': typeof import("bootstrap-vue-next")['BNavText']
    'LazyBNavbar': typeof import("bootstrap-vue-next")['BNavbar']
    'LazyBNavbarBrand': typeof import("bootstrap-vue-next")['BNavbarBrand']
    'LazyBNavbarNav': typeof import("bootstrap-vue-next")['BNavbarNav']
    'LazyBNavbarToggle': typeof import("bootstrap-vue-next")['BNavbarToggle']
    'LazyBOffcanvas': typeof import("bootstrap-vue-next")['BOffcanvas']
    'LazyBOverlay': typeof import("bootstrap-vue-next")['BOverlay']
    'LazyBPagination': typeof import("bootstrap-vue-next")['BPagination']
    'LazyBPlaceholder': typeof import("bootstrap-vue-next")['BPlaceholder']
    'LazyBPlaceholderButton': typeof import("bootstrap-vue-next")['BPlaceholderButton']
    'LazyBPlaceholderCard': typeof import("bootstrap-vue-next")['BPlaceholderCard']
    'LazyBPlaceholderTable': typeof import("bootstrap-vue-next")['BPlaceholderTable']
    'LazyBPlaceholderWrapper': typeof import("bootstrap-vue-next")['BPlaceholderWrapper']
    'LazyBPopover': typeof import("bootstrap-vue-next")['BPopover']
    'LazyBProgress': typeof import("bootstrap-vue-next")['BProgress']
    'LazyBProgressBar': typeof import("bootstrap-vue-next")['BProgressBar']
    'LazyBRow': typeof import("bootstrap-vue-next")['BRow']
    'LazyBSpinner': typeof import("bootstrap-vue-next")['BSpinner']
    'LazyBTab': typeof import("bootstrap-vue-next")['BTab']
    'LazyBTable': typeof import("bootstrap-vue-next")['BTable']
    'LazyBTableLite': typeof import("bootstrap-vue-next")['BTableLite']
    'LazyBTableSimple': typeof import("bootstrap-vue-next")['BTableSimple']
    'LazyBTabs': typeof import("bootstrap-vue-next")['BTabs']
    'LazyBTbody': typeof import("bootstrap-vue-next")['BTbody']
    'LazyBTd': typeof import("bootstrap-vue-next")['BTd']
    'LazyBTfoot': typeof import("bootstrap-vue-next")['BTfoot']
    'LazyBTh': typeof import("bootstrap-vue-next")['BTh']
    'LazyBThead': typeof import("bootstrap-vue-next")['BThead']
    'LazyBToast': typeof import("bootstrap-vue-next")['BToast']
    'LazyBToaster': typeof import("bootstrap-vue-next")['BToaster']
    'LazyBTooltip': typeof import("bootstrap-vue-next")['BTooltip']
    'LazyBTr': typeof import("bootstrap-vue-next")['BTr']
    'LazyBTransition': typeof import("bootstrap-vue-next")['BTransition']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BreadcrumbWidget: typeof import("../components/BreadcrumbWidget.vue")['default']
export const CreatePlaylist: typeof import("../components/CreatePlaylist.vue")['default']
export const CustomButton: typeof import("../components/CustomButton.vue")['default']
export const LoaderComponent: typeof import("../components/LoaderComponent.vue")['default']
export const MovieDescription: typeof import("../components/MovieDescription.vue")['default']
export const MovieSources: typeof import("../components/MovieSources.vue")['default']
export const SettingOffcanvas: typeof import("../components/SettingOffcanvas.vue")['default']
export const BlogDetailMetaList: typeof import("../components/blog/DetailMetaList.vue")['default']
export const BlogCommentsFormWidget: typeof import("../components/blog/comments/FormWidget.vue")['default']
export const BlogCommentsListWidget: typeof import("../components/blog/comments/ListWidget.vue")['default']
export const BlogSidebarAboutPage: typeof import("../components/blog/sidebar/AboutPage.vue")['default']
export const BlogSidebarArchiveWidget: typeof import("../components/blog/sidebar/ArchiveWidget.vue")['default']
export const BlogSidebarCategoriesWidget: typeof import("../components/blog/sidebar/CategoriesWidget.vue")['default']
export const BlogSidebarFollowUs: typeof import("../components/blog/sidebar/FollowUs.vue")['default']
export const BlogSidebarProductWidget: typeof import("../components/blog/sidebar/ProductWidget.vue")['default']
export const BlogSidebarRecentPost: typeof import("../components/blog/sidebar/RecentPost.vue")['default']
export const BlogSidebarRecentWidget: typeof import("../components/blog/sidebar/RecentWidget.vue")['default']
export const BlogSidebarTagsWidget: typeof import("../components/blog/sidebar/TagsWidget.vue")['default']
export const BrandLogo: typeof import("../components/brand/BrandLogo.vue")['default']
export const CardsCardBlogGrid: typeof import("../components/cards/CardBlogGrid.vue")['default']
export const CardsCardBlogList: typeof import("../components/cards/CardBlogList.vue")['default']
export const CardsCardCastGrid: typeof import("../components/cards/CardCastGrid.vue")['default']
export const CardsCardGenresGrid: typeof import("../components/cards/CardGenresGrid.vue")['default']
export const CardsCardStyle: typeof import("../components/cards/CardStyle.vue")['default']
export const CardsCastCard: typeof import("../components/cards/CastCard.vue")['default']
export const CardsContinueWatchCard: typeof import("../components/cards/ContinueWatchCard.vue")['default']
export const CardsEpisodeCard: typeof import("../components/cards/EpisodeCard.vue")['default']
export const CardsGenersCard: typeof import("../components/cards/GenersCard.vue")['default']
export const CardsPersonalityCard: typeof import("../components/cards/PersonalityCard.vue")['default']
export const CardsProfileCard: typeof import("../components/cards/ProfileCard.vue")['default']
export const CardsTagsCard: typeof import("../components/cards/TagsCard.vue")['default']
export const CardsTopTenCard: typeof import("../components/cards/TopTenCard.vue")['default']
export const CardsWatchlistCard: typeof import("../components/cards/WatchlistCard.vue")['default']
export const Counter: typeof import("../components/counter/Counter.vue")['default']
export const MerchandiseCategoryGridView: typeof import("../components/merchandise/CategoryGridView.vue")['default']
export const MerchandiseCategoryListView: typeof import("../components/merchandise/CategoryListView.vue")['default']
export const MerchandiseCheckoutCard: typeof import("../components/merchandise/CheckoutCard.vue")['default']
export const MerchandiseProductCard: typeof import("../components/merchandise/ProductCard.vue")['default']
export const MerchandiseProductFsLightBox: typeof import("../components/merchandise/ProductFsLightBox.vue")['default']
export const MerchandiseShopCategorySidebar: typeof import("../components/merchandise/ShopCategorySidebar.vue")['default']
export const MerchandiseWishlistCard: typeof import("../components/merchandise/WishlistCard.vue")['default']
export const MerchandiseCartTotal: typeof import("../components/merchandise/cart/CartTotal.vue")['default']
export const MerchandiseCartOffCanvasCart: typeof import("../components/merchandise/cart/OffCanvasCart.vue")['default']
export const MerchandiseCartProductCart: typeof import("../components/merchandise/cart/ProductCart.vue")['default']
export const MerchandisePartialsFooterMerchandise: typeof import("../components/merchandise/partials/FooterMerchandise.vue")['default']
export const MerchandisePartialsHeaderMerchandise: typeof import("../components/merchandise/partials/HeaderMerchandise.vue")['default']
export const PartialsFooterDefault: typeof import("../components/partials/FooterDefault.vue")['default']
export const PartialsHeaderDefault: typeof import("../components/partials/HeaderDefault.vue")['default']
export const PluginsVideoPlayer: typeof import("../components/plugins/VideoPlayer.vue")['default']
export const SectionsBestOfInternationalShows: typeof import("../components/sections/BestOfInternationalShows.vue")['default']
export const SectionsContinueWatching: typeof import("../components/sections/ContinueWatching.vue")['default']
export const SectionsLatestMovies: typeof import("../components/sections/LatestMovies.vue")['default']
export const SectionsMovieGeners: typeof import("../components/sections/MovieGeners.vue")['default']
export const SectionsMoviesRecommendedForYou: typeof import("../components/sections/MoviesRecommendedForYou.vue")['default']
export const SectionsOnlyOnStreamit: typeof import("../components/sections/OnlyOnStreamit.vue")['default']
export const SectionsParallexSection: typeof import("../components/sections/ParallexSection.vue")['default']
export const SectionsPopularMovies: typeof import("../components/sections/PopularMovies.vue")['default']
export const SectionsPopularVideos: typeof import("../components/sections/PopularVideos.vue")['default']
export const SectionsProductSection: typeof import("../components/sections/ProductSection.vue")['default']
export const SectionsRecommendedForYou: typeof import("../components/sections/RecommendedForYou.vue")['default']
export const SectionsRecommendedTVShow: typeof import("../components/sections/RecommendedTVShow.vue")['default']
export const SectionsShowsWeRecommend: typeof import("../components/sections/ShowsWeRecommend.vue")['default']
export const SectionsSpecials&LatestMovies: typeof import("../components/sections/Specials&LatestMovies.vue")['default']
export const SectionsSuggestedBlock: typeof import("../components/sections/SuggestedBlock.vue")['default']
export const SectionsTVPopularShows: typeof import("../components/sections/TVPopularShows.vue")['default']
export const SectionsTabSlider: typeof import("../components/sections/TabSlider.vue")['default']
export const SectionsTopPicsForYou: typeof import("../components/sections/TopPicsForYou.vue")['default']
export const SectionsTopTenMoviesToWatch: typeof import("../components/sections/TopTenMoviesToWatch.vue")['default']
export const SectionsTrendingSection: typeof import("../components/sections/TrendingSection.vue")['default']
export const SectionsUpcomingMovies: typeof import("../components/sections/UpcomingMovies.vue")['default']
export const SectionsVideosRecommendedForYou: typeof import("../components/sections/VideosRecommendedForYou.vue")['default']
export const SectionsYourFavouritePersonality: typeof import("../components/sections/YourFavouritePersonality.vue")['default']
export const SliderHomeHeroSlider: typeof import("../components/slider/HomeHeroSlider.vue")['default']
export const SliderHomeVerticalSlider: typeof import("../components/slider/HomeVerticalSlider.vue")['default']
export const SliderMovieHeroSlider: typeof import("../components/slider/MovieHeroSlider.vue")['default']
export const SliderOttHeroSlider: typeof import("../components/slider/OttHeroSlider.vue")['default']
export const SliderSectionSlider: typeof import("../components/slider/SectionSlider.vue")['default']
export const SliderShopHeroProductSlider: typeof import("../components/slider/ShopHeroProductSlider.vue")['default']
export const SliderTvShowHeroSlider: typeof import("../components/slider/TvShowHeroSlider.vue")['default']
export const SliderVerticalSectionSlider: typeof import("../components/slider/VerticalSectionSlider.vue")['default']
export const SliderVideoHeroSlider: typeof import("../components/slider/VideoHeroSlider.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const BAccordion: typeof import("bootstrap-vue-next")['BAccordion']
export const BAccordionItem: typeof import("bootstrap-vue-next")['BAccordionItem']
export const BAlert: typeof import("bootstrap-vue-next")['BAlert']
export const BAvatar: typeof import("bootstrap-vue-next")['BAvatar']
export const BAvatarGroup: typeof import("bootstrap-vue-next")['BAvatarGroup']
export const BBadge: typeof import("bootstrap-vue-next")['BBadge']
export const BBreadcrumb: typeof import("bootstrap-vue-next")['BBreadcrumb']
export const BBreadcrumbItem: typeof import("bootstrap-vue-next")['BBreadcrumbItem']
export const BButton: typeof import("bootstrap-vue-next")['BButton']
export const BButtonGroup: typeof import("bootstrap-vue-next")['BButtonGroup']
export const BButtonToolbar: typeof import("bootstrap-vue-next")['BButtonToolbar']
export const BCard: typeof import("bootstrap-vue-next")['BCard']
export const BCardBody: typeof import("bootstrap-vue-next")['BCardBody']
export const BCardFooter: typeof import("bootstrap-vue-next")['BCardFooter']
export const BCardGroup: typeof import("bootstrap-vue-next")['BCardGroup']
export const BCardHeader: typeof import("bootstrap-vue-next")['BCardHeader']
export const BCardImg: typeof import("bootstrap-vue-next")['BCardImg']
export const BCardSubtitle: typeof import("bootstrap-vue-next")['BCardSubtitle']
export const BCardText: typeof import("bootstrap-vue-next")['BCardText']
export const BCardTitle: typeof import("bootstrap-vue-next")['BCardTitle']
export const BCarousel: typeof import("bootstrap-vue-next")['BCarousel']
export const BCarouselSlide: typeof import("bootstrap-vue-next")['BCarouselSlide']
export const BCloseButton: typeof import("bootstrap-vue-next")['BCloseButton']
export const BCol: typeof import("bootstrap-vue-next")['BCol']
export const BCollapse: typeof import("bootstrap-vue-next")['BCollapse']
export const BContainer: typeof import("bootstrap-vue-next")['BContainer']
export const BDropdown: typeof import("bootstrap-vue-next")['BDropdown']
export const BDropdownDivider: typeof import("bootstrap-vue-next")['BDropdownDivider']
export const BDropdownForm: typeof import("bootstrap-vue-next")['BDropdownForm']
export const BDropdownGroup: typeof import("bootstrap-vue-next")['BDropdownGroup']
export const BDropdownHeader: typeof import("bootstrap-vue-next")['BDropdownHeader']
export const BDropdownItem: typeof import("bootstrap-vue-next")['BDropdownItem']
export const BDropdownItemButton: typeof import("bootstrap-vue-next")['BDropdownItemButton']
export const BDropdownText: typeof import("bootstrap-vue-next")['BDropdownText']
export const BForm: typeof import("bootstrap-vue-next")['BForm']
export const BFormCheckbox: typeof import("bootstrap-vue-next")['BFormCheckbox']
export const BFormCheckboxGroup: typeof import("bootstrap-vue-next")['BFormCheckboxGroup']
export const BFormFile: typeof import("bootstrap-vue-next")['BFormFile']
export const BFormFloatingLabel: typeof import("bootstrap-vue-next")['BFormFloatingLabel']
export const BFormGroup: typeof import("bootstrap-vue-next")['BFormGroup']
export const BFormInput: typeof import("bootstrap-vue-next")['BFormInput']
export const BFormInvalidFeedback: typeof import("bootstrap-vue-next")['BFormInvalidFeedback']
export const BFormRadio: typeof import("bootstrap-vue-next")['BFormRadio']
export const BFormRadioGroup: typeof import("bootstrap-vue-next")['BFormRadioGroup']
export const BFormRow: typeof import("bootstrap-vue-next")['BFormRow']
export const BFormSelect: typeof import("bootstrap-vue-next")['BFormSelect']
export const BFormSelectOption: typeof import("bootstrap-vue-next")['BFormSelectOption']
export const BFormSelectOptionGroup: typeof import("bootstrap-vue-next")['BFormSelectOptionGroup']
export const BFormSpinbutton: typeof import("bootstrap-vue-next")['BFormSpinbutton']
export const BFormTag: typeof import("bootstrap-vue-next")['BFormTag']
export const BFormTags: typeof import("bootstrap-vue-next")['BFormTags']
export const BFormText: typeof import("bootstrap-vue-next")['BFormText']
export const BFormTextarea: typeof import("bootstrap-vue-next")['BFormTextarea']
export const BFormValidFeedback: typeof import("bootstrap-vue-next")['BFormValidFeedback']
export const BImg: typeof import("bootstrap-vue-next")['BImg']
export const BInputGroup: typeof import("bootstrap-vue-next")['BInputGroup']
export const BInputGroupAddon: typeof import("bootstrap-vue-next")['BInputGroupAddon']
export const BInputGroupAppend: typeof import("bootstrap-vue-next")['BInputGroupAppend']
export const BInputGroupPrepend: typeof import("bootstrap-vue-next")['BInputGroupPrepend']
export const BInputGroupText: typeof import("bootstrap-vue-next")['BInputGroupText']
export const BLink: typeof import("bootstrap-vue-next")['BLink']
export const BListGroup: typeof import("bootstrap-vue-next")['BListGroup']
export const BListGroupItem: typeof import("bootstrap-vue-next")['BListGroupItem']
export const BModal: typeof import("bootstrap-vue-next")['BModal']
export const BNav: typeof import("bootstrap-vue-next")['BNav']
export const BNavForm: typeof import("bootstrap-vue-next")['BNavForm']
export const BNavItem: typeof import("bootstrap-vue-next")['BNavItem']
export const BNavItemDropdown: typeof import("bootstrap-vue-next")['BNavItemDropdown']
export const BNavText: typeof import("bootstrap-vue-next")['BNavText']
export const BNavbar: typeof import("bootstrap-vue-next")['BNavbar']
export const BNavbarBrand: typeof import("bootstrap-vue-next")['BNavbarBrand']
export const BNavbarNav: typeof import("bootstrap-vue-next")['BNavbarNav']
export const BNavbarToggle: typeof import("bootstrap-vue-next")['BNavbarToggle']
export const BOffcanvas: typeof import("bootstrap-vue-next")['BOffcanvas']
export const BOverlay: typeof import("bootstrap-vue-next")['BOverlay']
export const BPagination: typeof import("bootstrap-vue-next")['BPagination']
export const BPlaceholder: typeof import("bootstrap-vue-next")['BPlaceholder']
export const BPlaceholderButton: typeof import("bootstrap-vue-next")['BPlaceholderButton']
export const BPlaceholderCard: typeof import("bootstrap-vue-next")['BPlaceholderCard']
export const BPlaceholderTable: typeof import("bootstrap-vue-next")['BPlaceholderTable']
export const BPlaceholderWrapper: typeof import("bootstrap-vue-next")['BPlaceholderWrapper']
export const BPopover: typeof import("bootstrap-vue-next")['BPopover']
export const BProgress: typeof import("bootstrap-vue-next")['BProgress']
export const BProgressBar: typeof import("bootstrap-vue-next")['BProgressBar']
export const BRow: typeof import("bootstrap-vue-next")['BRow']
export const BSpinner: typeof import("bootstrap-vue-next")['BSpinner']
export const BTab: typeof import("bootstrap-vue-next")['BTab']
export const BTable: typeof import("bootstrap-vue-next")['BTable']
export const BTableLite: typeof import("bootstrap-vue-next")['BTableLite']
export const BTableSimple: typeof import("bootstrap-vue-next")['BTableSimple']
export const BTabs: typeof import("bootstrap-vue-next")['BTabs']
export const BTbody: typeof import("bootstrap-vue-next")['BTbody']
export const BTd: typeof import("bootstrap-vue-next")['BTd']
export const BTfoot: typeof import("bootstrap-vue-next")['BTfoot']
export const BTh: typeof import("bootstrap-vue-next")['BTh']
export const BThead: typeof import("bootstrap-vue-next")['BThead']
export const BToast: typeof import("bootstrap-vue-next")['BToast']
export const BToaster: typeof import("bootstrap-vue-next")['BToaster']
export const BTooltip: typeof import("bootstrap-vue-next")['BTooltip']
export const BTr: typeof import("bootstrap-vue-next")['BTr']
export const BTransition: typeof import("bootstrap-vue-next")['BTransition']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBreadcrumbWidget: typeof import("../components/BreadcrumbWidget.vue")['default']
export const LazyCreatePlaylist: typeof import("../components/CreatePlaylist.vue")['default']
export const LazyCustomButton: typeof import("../components/CustomButton.vue")['default']
export const LazyLoaderComponent: typeof import("../components/LoaderComponent.vue")['default']
export const LazyMovieDescription: typeof import("../components/MovieDescription.vue")['default']
export const LazyMovieSources: typeof import("../components/MovieSources.vue")['default']
export const LazySettingOffcanvas: typeof import("../components/SettingOffcanvas.vue")['default']
export const LazyBlogDetailMetaList: typeof import("../components/blog/DetailMetaList.vue")['default']
export const LazyBlogCommentsFormWidget: typeof import("../components/blog/comments/FormWidget.vue")['default']
export const LazyBlogCommentsListWidget: typeof import("../components/blog/comments/ListWidget.vue")['default']
export const LazyBlogSidebarAboutPage: typeof import("../components/blog/sidebar/AboutPage.vue")['default']
export const LazyBlogSidebarArchiveWidget: typeof import("../components/blog/sidebar/ArchiveWidget.vue")['default']
export const LazyBlogSidebarCategoriesWidget: typeof import("../components/blog/sidebar/CategoriesWidget.vue")['default']
export const LazyBlogSidebarFollowUs: typeof import("../components/blog/sidebar/FollowUs.vue")['default']
export const LazyBlogSidebarProductWidget: typeof import("../components/blog/sidebar/ProductWidget.vue")['default']
export const LazyBlogSidebarRecentPost: typeof import("../components/blog/sidebar/RecentPost.vue")['default']
export const LazyBlogSidebarRecentWidget: typeof import("../components/blog/sidebar/RecentWidget.vue")['default']
export const LazyBlogSidebarTagsWidget: typeof import("../components/blog/sidebar/TagsWidget.vue")['default']
export const LazyBrandLogo: typeof import("../components/brand/BrandLogo.vue")['default']
export const LazyCardsCardBlogGrid: typeof import("../components/cards/CardBlogGrid.vue")['default']
export const LazyCardsCardBlogList: typeof import("../components/cards/CardBlogList.vue")['default']
export const LazyCardsCardCastGrid: typeof import("../components/cards/CardCastGrid.vue")['default']
export const LazyCardsCardGenresGrid: typeof import("../components/cards/CardGenresGrid.vue")['default']
export const LazyCardsCardStyle: typeof import("../components/cards/CardStyle.vue")['default']
export const LazyCardsCastCard: typeof import("../components/cards/CastCard.vue")['default']
export const LazyCardsContinueWatchCard: typeof import("../components/cards/ContinueWatchCard.vue")['default']
export const LazyCardsEpisodeCard: typeof import("../components/cards/EpisodeCard.vue")['default']
export const LazyCardsGenersCard: typeof import("../components/cards/GenersCard.vue")['default']
export const LazyCardsPersonalityCard: typeof import("../components/cards/PersonalityCard.vue")['default']
export const LazyCardsProfileCard: typeof import("../components/cards/ProfileCard.vue")['default']
export const LazyCardsTagsCard: typeof import("../components/cards/TagsCard.vue")['default']
export const LazyCardsTopTenCard: typeof import("../components/cards/TopTenCard.vue")['default']
export const LazyCardsWatchlistCard: typeof import("../components/cards/WatchlistCard.vue")['default']
export const LazyCounter: typeof import("../components/counter/Counter.vue")['default']
export const LazyMerchandiseCategoryGridView: typeof import("../components/merchandise/CategoryGridView.vue")['default']
export const LazyMerchandiseCategoryListView: typeof import("../components/merchandise/CategoryListView.vue")['default']
export const LazyMerchandiseCheckoutCard: typeof import("../components/merchandise/CheckoutCard.vue")['default']
export const LazyMerchandiseProductCard: typeof import("../components/merchandise/ProductCard.vue")['default']
export const LazyMerchandiseProductFsLightBox: typeof import("../components/merchandise/ProductFsLightBox.vue")['default']
export const LazyMerchandiseShopCategorySidebar: typeof import("../components/merchandise/ShopCategorySidebar.vue")['default']
export const LazyMerchandiseWishlistCard: typeof import("../components/merchandise/WishlistCard.vue")['default']
export const LazyMerchandiseCartTotal: typeof import("../components/merchandise/cart/CartTotal.vue")['default']
export const LazyMerchandiseCartOffCanvasCart: typeof import("../components/merchandise/cart/OffCanvasCart.vue")['default']
export const LazyMerchandiseCartProductCart: typeof import("../components/merchandise/cart/ProductCart.vue")['default']
export const LazyMerchandisePartialsFooterMerchandise: typeof import("../components/merchandise/partials/FooterMerchandise.vue")['default']
export const LazyMerchandisePartialsHeaderMerchandise: typeof import("../components/merchandise/partials/HeaderMerchandise.vue")['default']
export const LazyPartialsFooterDefault: typeof import("../components/partials/FooterDefault.vue")['default']
export const LazyPartialsHeaderDefault: typeof import("../components/partials/HeaderDefault.vue")['default']
export const LazyPluginsVideoPlayer: typeof import("../components/plugins/VideoPlayer.vue")['default']
export const LazySectionsBestOfInternationalShows: typeof import("../components/sections/BestOfInternationalShows.vue")['default']
export const LazySectionsContinueWatching: typeof import("../components/sections/ContinueWatching.vue")['default']
export const LazySectionsLatestMovies: typeof import("../components/sections/LatestMovies.vue")['default']
export const LazySectionsMovieGeners: typeof import("../components/sections/MovieGeners.vue")['default']
export const LazySectionsMoviesRecommendedForYou: typeof import("../components/sections/MoviesRecommendedForYou.vue")['default']
export const LazySectionsOnlyOnStreamit: typeof import("../components/sections/OnlyOnStreamit.vue")['default']
export const LazySectionsParallexSection: typeof import("../components/sections/ParallexSection.vue")['default']
export const LazySectionsPopularMovies: typeof import("../components/sections/PopularMovies.vue")['default']
export const LazySectionsPopularVideos: typeof import("../components/sections/PopularVideos.vue")['default']
export const LazySectionsProductSection: typeof import("../components/sections/ProductSection.vue")['default']
export const LazySectionsRecommendedForYou: typeof import("../components/sections/RecommendedForYou.vue")['default']
export const LazySectionsRecommendedTVShow: typeof import("../components/sections/RecommendedTVShow.vue")['default']
export const LazySectionsShowsWeRecommend: typeof import("../components/sections/ShowsWeRecommend.vue")['default']
export const LazySectionsSpecials&LatestMovies: typeof import("../components/sections/Specials&LatestMovies.vue")['default']
export const LazySectionsSuggestedBlock: typeof import("../components/sections/SuggestedBlock.vue")['default']
export const LazySectionsTVPopularShows: typeof import("../components/sections/TVPopularShows.vue")['default']
export const LazySectionsTabSlider: typeof import("../components/sections/TabSlider.vue")['default']
export const LazySectionsTopPicsForYou: typeof import("../components/sections/TopPicsForYou.vue")['default']
export const LazySectionsTopTenMoviesToWatch: typeof import("../components/sections/TopTenMoviesToWatch.vue")['default']
export const LazySectionsTrendingSection: typeof import("../components/sections/TrendingSection.vue")['default']
export const LazySectionsUpcomingMovies: typeof import("../components/sections/UpcomingMovies.vue")['default']
export const LazySectionsVideosRecommendedForYou: typeof import("../components/sections/VideosRecommendedForYou.vue")['default']
export const LazySectionsYourFavouritePersonality: typeof import("../components/sections/YourFavouritePersonality.vue")['default']
export const LazySliderHomeHeroSlider: typeof import("../components/slider/HomeHeroSlider.vue")['default']
export const LazySliderHomeVerticalSlider: typeof import("../components/slider/HomeVerticalSlider.vue")['default']
export const LazySliderMovieHeroSlider: typeof import("../components/slider/MovieHeroSlider.vue")['default']
export const LazySliderOttHeroSlider: typeof import("../components/slider/OttHeroSlider.vue")['default']
export const LazySliderSectionSlider: typeof import("../components/slider/SectionSlider.vue")['default']
export const LazySliderShopHeroProductSlider: typeof import("../components/slider/ShopHeroProductSlider.vue")['default']
export const LazySliderTvShowHeroSlider: typeof import("../components/slider/TvShowHeroSlider.vue")['default']
export const LazySliderVerticalSectionSlider: typeof import("../components/slider/VerticalSectionSlider.vue")['default']
export const LazySliderVideoHeroSlider: typeof import("../components/slider/VideoHeroSlider.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyBAccordion: typeof import("bootstrap-vue-next")['BAccordion']
export const LazyBAccordionItem: typeof import("bootstrap-vue-next")['BAccordionItem']
export const LazyBAlert: typeof import("bootstrap-vue-next")['BAlert']
export const LazyBAvatar: typeof import("bootstrap-vue-next")['BAvatar']
export const LazyBAvatarGroup: typeof import("bootstrap-vue-next")['BAvatarGroup']
export const LazyBBadge: typeof import("bootstrap-vue-next")['BBadge']
export const LazyBBreadcrumb: typeof import("bootstrap-vue-next")['BBreadcrumb']
export const LazyBBreadcrumbItem: typeof import("bootstrap-vue-next")['BBreadcrumbItem']
export const LazyBButton: typeof import("bootstrap-vue-next")['BButton']
export const LazyBButtonGroup: typeof import("bootstrap-vue-next")['BButtonGroup']
export const LazyBButtonToolbar: typeof import("bootstrap-vue-next")['BButtonToolbar']
export const LazyBCard: typeof import("bootstrap-vue-next")['BCard']
export const LazyBCardBody: typeof import("bootstrap-vue-next")['BCardBody']
export const LazyBCardFooter: typeof import("bootstrap-vue-next")['BCardFooter']
export const LazyBCardGroup: typeof import("bootstrap-vue-next")['BCardGroup']
export const LazyBCardHeader: typeof import("bootstrap-vue-next")['BCardHeader']
export const LazyBCardImg: typeof import("bootstrap-vue-next")['BCardImg']
export const LazyBCardSubtitle: typeof import("bootstrap-vue-next")['BCardSubtitle']
export const LazyBCardText: typeof import("bootstrap-vue-next")['BCardText']
export const LazyBCardTitle: typeof import("bootstrap-vue-next")['BCardTitle']
export const LazyBCarousel: typeof import("bootstrap-vue-next")['BCarousel']
export const LazyBCarouselSlide: typeof import("bootstrap-vue-next")['BCarouselSlide']
export const LazyBCloseButton: typeof import("bootstrap-vue-next")['BCloseButton']
export const LazyBCol: typeof import("bootstrap-vue-next")['BCol']
export const LazyBCollapse: typeof import("bootstrap-vue-next")['BCollapse']
export const LazyBContainer: typeof import("bootstrap-vue-next")['BContainer']
export const LazyBDropdown: typeof import("bootstrap-vue-next")['BDropdown']
export const LazyBDropdownDivider: typeof import("bootstrap-vue-next")['BDropdownDivider']
export const LazyBDropdownForm: typeof import("bootstrap-vue-next")['BDropdownForm']
export const LazyBDropdownGroup: typeof import("bootstrap-vue-next")['BDropdownGroup']
export const LazyBDropdownHeader: typeof import("bootstrap-vue-next")['BDropdownHeader']
export const LazyBDropdownItem: typeof import("bootstrap-vue-next")['BDropdownItem']
export const LazyBDropdownItemButton: typeof import("bootstrap-vue-next")['BDropdownItemButton']
export const LazyBDropdownText: typeof import("bootstrap-vue-next")['BDropdownText']
export const LazyBForm: typeof import("bootstrap-vue-next")['BForm']
export const LazyBFormCheckbox: typeof import("bootstrap-vue-next")['BFormCheckbox']
export const LazyBFormCheckboxGroup: typeof import("bootstrap-vue-next")['BFormCheckboxGroup']
export const LazyBFormFile: typeof import("bootstrap-vue-next")['BFormFile']
export const LazyBFormFloatingLabel: typeof import("bootstrap-vue-next")['BFormFloatingLabel']
export const LazyBFormGroup: typeof import("bootstrap-vue-next")['BFormGroup']
export const LazyBFormInput: typeof import("bootstrap-vue-next")['BFormInput']
export const LazyBFormInvalidFeedback: typeof import("bootstrap-vue-next")['BFormInvalidFeedback']
export const LazyBFormRadio: typeof import("bootstrap-vue-next")['BFormRadio']
export const LazyBFormRadioGroup: typeof import("bootstrap-vue-next")['BFormRadioGroup']
export const LazyBFormRow: typeof import("bootstrap-vue-next")['BFormRow']
export const LazyBFormSelect: typeof import("bootstrap-vue-next")['BFormSelect']
export const LazyBFormSelectOption: typeof import("bootstrap-vue-next")['BFormSelectOption']
export const LazyBFormSelectOptionGroup: typeof import("bootstrap-vue-next")['BFormSelectOptionGroup']
export const LazyBFormSpinbutton: typeof import("bootstrap-vue-next")['BFormSpinbutton']
export const LazyBFormTag: typeof import("bootstrap-vue-next")['BFormTag']
export const LazyBFormTags: typeof import("bootstrap-vue-next")['BFormTags']
export const LazyBFormText: typeof import("bootstrap-vue-next")['BFormText']
export const LazyBFormTextarea: typeof import("bootstrap-vue-next")['BFormTextarea']
export const LazyBFormValidFeedback: typeof import("bootstrap-vue-next")['BFormValidFeedback']
export const LazyBImg: typeof import("bootstrap-vue-next")['BImg']
export const LazyBInputGroup: typeof import("bootstrap-vue-next")['BInputGroup']
export const LazyBInputGroupAddon: typeof import("bootstrap-vue-next")['BInputGroupAddon']
export const LazyBInputGroupAppend: typeof import("bootstrap-vue-next")['BInputGroupAppend']
export const LazyBInputGroupPrepend: typeof import("bootstrap-vue-next")['BInputGroupPrepend']
export const LazyBInputGroupText: typeof import("bootstrap-vue-next")['BInputGroupText']
export const LazyBLink: typeof import("bootstrap-vue-next")['BLink']
export const LazyBListGroup: typeof import("bootstrap-vue-next")['BListGroup']
export const LazyBListGroupItem: typeof import("bootstrap-vue-next")['BListGroupItem']
export const LazyBModal: typeof import("bootstrap-vue-next")['BModal']
export const LazyBNav: typeof import("bootstrap-vue-next")['BNav']
export const LazyBNavForm: typeof import("bootstrap-vue-next")['BNavForm']
export const LazyBNavItem: typeof import("bootstrap-vue-next")['BNavItem']
export const LazyBNavItemDropdown: typeof import("bootstrap-vue-next")['BNavItemDropdown']
export const LazyBNavText: typeof import("bootstrap-vue-next")['BNavText']
export const LazyBNavbar: typeof import("bootstrap-vue-next")['BNavbar']
export const LazyBNavbarBrand: typeof import("bootstrap-vue-next")['BNavbarBrand']
export const LazyBNavbarNav: typeof import("bootstrap-vue-next")['BNavbarNav']
export const LazyBNavbarToggle: typeof import("bootstrap-vue-next")['BNavbarToggle']
export const LazyBOffcanvas: typeof import("bootstrap-vue-next")['BOffcanvas']
export const LazyBOverlay: typeof import("bootstrap-vue-next")['BOverlay']
export const LazyBPagination: typeof import("bootstrap-vue-next")['BPagination']
export const LazyBPlaceholder: typeof import("bootstrap-vue-next")['BPlaceholder']
export const LazyBPlaceholderButton: typeof import("bootstrap-vue-next")['BPlaceholderButton']
export const LazyBPlaceholderCard: typeof import("bootstrap-vue-next")['BPlaceholderCard']
export const LazyBPlaceholderTable: typeof import("bootstrap-vue-next")['BPlaceholderTable']
export const LazyBPlaceholderWrapper: typeof import("bootstrap-vue-next")['BPlaceholderWrapper']
export const LazyBPopover: typeof import("bootstrap-vue-next")['BPopover']
export const LazyBProgress: typeof import("bootstrap-vue-next")['BProgress']
export const LazyBProgressBar: typeof import("bootstrap-vue-next")['BProgressBar']
export const LazyBRow: typeof import("bootstrap-vue-next")['BRow']
export const LazyBSpinner: typeof import("bootstrap-vue-next")['BSpinner']
export const LazyBTab: typeof import("bootstrap-vue-next")['BTab']
export const LazyBTable: typeof import("bootstrap-vue-next")['BTable']
export const LazyBTableLite: typeof import("bootstrap-vue-next")['BTableLite']
export const LazyBTableSimple: typeof import("bootstrap-vue-next")['BTableSimple']
export const LazyBTabs: typeof import("bootstrap-vue-next")['BTabs']
export const LazyBTbody: typeof import("bootstrap-vue-next")['BTbody']
export const LazyBTd: typeof import("bootstrap-vue-next")['BTd']
export const LazyBTfoot: typeof import("bootstrap-vue-next")['BTfoot']
export const LazyBTh: typeof import("bootstrap-vue-next")['BTh']
export const LazyBThead: typeof import("bootstrap-vue-next")['BThead']
export const LazyBToast: typeof import("bootstrap-vue-next")['BToast']
export const LazyBToaster: typeof import("bootstrap-vue-next")['BToaster']
export const LazyBTooltip: typeof import("bootstrap-vue-next")['BTooltip']
export const LazyBTr: typeof import("bootstrap-vue-next")['BTr']
export const LazyBTransition: typeof import("bootstrap-vue-next")['BTransition']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
